agent:
  name: brodagroupsoftware:agent-bank-initial-deposit
  purpose: |
    This agent is an expert in making a deposit into a bank account for a bank account open process.
  description: |
    This agent will create the account and make an initial deposit into the account.
    This agent knows where all of the account databases reside and knows how to deposit funds in them.
  module: tools.brodagroupsoftware.agent.tool
  url: http://agent-bank-initial-deposit:8000
  version: v0.0.1
  approach: |
    The following steps are required to perform this process:
    1. Identify the tool to deposit money into account. The tool for this is 'tool.bank.initial_deposit'
    2. Execute tool to deposit money into account
  parameters:
    - name: customer_name
      type: string
      description: "The name of the customer"
    - name: amount
      type: float
      description: "The deposit amount"
  tools:
    - name: tool.llm
      purpose: To think, determine task plans
      description: Process natural language requests using a Large Language Model
      module: tools.brodagroupsoftware.llm.tool
    - name: tool.bank.initial_deposit
      purpose: Perform initial deposit to bank account
      description: Perform initial deposit to bank account
      module: tools.brodagroupsoftware.bank.initial_deposit
  agents: []
  logging: INFO

registry:
  # host: localhost
  host: xagenticmesh-registry
  port: 8000
  retry_interval: 10  # seconds
  refresh_timeout: 300

monitor:
  # host: localhost
  host: xagenticmesh-monitor
  port: 8000
  retry_interval: 10  # seconds
  refresh_timeout: 15
