agent:
  name: brodagroupsoftware:agent-bank-notification
  purpose: |
    This agent is an expert in notifying customers of important information.
  description: |
    This agent will notify a customer of the completed process.
    In addition this agent can notify customers of any questions, required data, or
    informational posts, that are needed during a bank account open process.
  module: tools.brodagroupsoftware.agent.tool
  url: http://agent-bank-notification:8000
  version: v0.0.1
  approach: |
    The following steps are required to perform this process:
    1. Identify the tool to notify the customer. The tool for this is 'tool.bank.notification'
    2. Execute tool to notify the customer
  parameters:
    - name: customer_name
      type: string
      description: "The name of the customer"
  tools:
    - name: tool.llm
      purpose: To think, determine task plans
      description: Process natural language requests using a Large Language Model
      module: tools.brodagroupsoftware.llm.tool
    - name: tool.bank.notification
      purpose: Notify a customer
      description: Notify a customer
      module: tools.brodagroupsoftware.bank.notification
  agents: []
  logging: INFO

registry:
  # host: localhost
  host: xagenticmesh-registry
  port: 8000
  retry_interval: 10  # seconds
  refresh_timeout: 300

monitor:
  # host: localhost
  host: xagenticmesh-monitor
  port: 8000
  retry_interval: 10  # seconds
  refresh_timeout: 15
